Add `TypedDataUtils.encodeType` tests
MetaMask/eth-sig-util pull request #167
Opened 2021-08-11 22:26 UTC by Gudahtt

Comprehensive unit tests have been added for `encodeType`. Invocations of `encodeType` in the other signature tests have been removed, as they're now redundant.

2021-08-11 22:26 UTC, Gudahtt commented
This depends upon #164

2021-08-15 17:33 UTC, rekmarks requested changes
Just one minor request, otherwise LGTM!

2021-08-15 17:33 UTC, rekmarks commented on src/index.test.ts
> +  it('should encode unrecognized types', () => {
I did a double-take reading this and the missing primary type test case, and we can spare future readers the trouble:

```suggestion
  it('should encode unrecognized non-primary types', () => {
```

2021-08-15 17:36 UTC, rekmarks approved these changes
I'm gonna go ahead and guess that @Gudahtt will be OK with the change that I wanted, so I merged it and am now approving the PR.

2021-08-16 11:58 UTC, merged