Adds `signAuthorization` method for EIP-7702
MetaMask/eth-sig-util pull request #407
Opened 2024-12-19 04:11 UTC by jeffsmale90

EIP-7702 defines a new struct `Authorization` which represents authority to set a pointer to a contract address at an EOA - effectively making the EOA perform as a smart contract.

This change adds methods to hash and sign authorizations, and to recover signer address.

Although the EIP defines the signed authorization as `[chain_id, address, nonce, y_parity, r, s]`, the utility method returns the signature as a standard `r|s|v` signature for consistency with other signing methods.

See https://github.com/ethereum/EIPs/blob/master/EIPS/eip-7702.md for details

2024-12-19 04:34 UTC, jeffsmale90 commented on src/sign-authorization.ts
> + * The signature format follows EIP-155 for chain-specific signatures.
```suggestion
```

2025-01-06 10:32 UTC, matthewwalsh0 requested changes

2025-01-06 10:32 UTC, matthewwalsh0 commented on src/sign-authorization.ts
> +export type Authorization = [
Minor, could `Authorization` be or become too generic a term in the context of signing?

Should we call this something like `EIP7702Authorization`?
Maybe `7702` as the filename?

2025-01-06 10:32 UTC, matthewwalsh0 commented on src/sign-authorization.ts
> +function validateAuthorization(authorization: Authorization) {
Minor, non-exported functions at the bottom of the file to highlight what is used externally?

2025-01-06 10:32 UTC, matthewwalsh0 commented on src/sign-authorization.ts
> +  if (isNullish(chainId)) {
Do we definitely want to support / encourage cross-chain authorizations via the `0` chain ID?

Could we also validate it's not zero at this package level?

2025-01-06 10:32 UTC, matthewwalsh0 commented on src/sign-authorization.ts
> +export function signAuthorization({
Minor, maybe `sign7702Authorization` and the same format for the other functions?

Just to add more clarity if we get other types of authorization in future?

2025-01-06 10:32 UTC, matthewwalsh0 commented on src/sign-authorization.test.ts
> +const expectedSignature =
Minor, capitals and underscores for constants so `EXPECTED_SIGNATURE` etc?

2025-01-06 10:32 UTC, matthewwalsh0 commented on src/sign-authorization.test.ts
> +    it('should produce the correct signature', () => {
Minor, `should` is redundant in test names?  `produces the correct signature` for example.

2025-01-06 10:32 UTC, matthewwalsh0 commented on src/sign-authorization.test.ts
> +    for (const [label, authorization] of Object.entries(testCases)) {
Minor, could also use a `it.each`.

2025-01-13 21:41 UTC, jeffsmale90 commented on src/sign-authorization.ts
> +  if (isNullish(chainId)) {
I am not sure whether or not we want to support chainId 0 - there's an argument for it, even though it's problematic (nonce likely won't match across all chains).

My preference is to support it at the utility level, and make the decision at the API level.

2025-01-13 21:46 UTC, jeffsmale90 commented on src/sign-authorization.ts
> +export type Authorization = [
Yeah, I think that makes sense - it's already a bit of an overloaded term.

2025-01-13 21:56 UTC, jeffsmale90 commented on src/sign-authorization.test.ts
> +    it('should produce the correct signature', () => {
You are correct - it could be removed, but `should` is consistent across all of the existing tests 🤷

2025-01-13 21:59 UTC, jeffsmale90 commented on src/sign-authorization.ts
> +export type Authorization = [
I named the file `sign-eip7702-authorization.ts` for a combination of clarity and consistency with the other signing files.

2025-01-13 22:03 UTC, jeffsmale90 commented
@matthewwalsh0 thanks for the review! I made all of the changes you recommended, except for validating chainId !== 0, as I think this should be an API concern, rather than a utility concern.

2025-01-24 10:15 UTC, matthewwalsh0 commented on src/sign-authorization.test.ts
> +    it('should produce the correct signature', () => {
It's a legacy pattern in lots of repositories that we're slowing moving aways from, but not urgent now.

2025-01-24 10:16 UTC, matthewwalsh0 approved these changes

2025-01-26 22:22 UTC, merged